# Generated by Django 4.2.1 on 2023-06-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_contactus_alter_user_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='date',
        ),
    ]
