# Generated by Django 4.2.1 on 2023-06-01 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_contact_delete_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
