# Generated by Django 4.2.1 on 2023-06-01 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='comment_unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
