# Generated by Django 4.2.1 on 2023-06-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0022_comment_likes_comment_unlikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='unlikes',
        ),
    ]
